-- Creates dns records for each section
function pps_sections(target)
  -- A records
  alias("ag", target)
  alias("ai", target)
  alias("ar", target)
  alias("bb", target)
  alias("be", target)
  alias("bern.be", target)
  alias("bl", target)
  alias("bs", target)
  alias("fr", target)
  alias("ge", target)
  alias("gl", target)
  alias("gr", target)
  alias("ju", target)
  alias("lu", target)
  alias("ne", target)
  alias("nw", target)
  alias("ow", target)
  alias("sg", target)
  alias("sh", target)
  alias("so", target)
  alias("stadt.zh", target)
  alias("steinhausen", target)
  alias("sz", target)
  alias("tg", target)
  alias("ti", target)
  alias("ur", target)
  alias("vd", target)
  alias("vs", target)
  alias("winterthur.zh", target)
  alias("zg", target)
  alias("zh", target)
  alias("zs", target)

  -- MX records
  mx("ag", "s034.cyon.net", 10)
  mx("ai", "s034.cyon.net", 10)
  mx("ar", "s034.cyon.net", 10)
  mx("bb", "s034.cyon.net", 10)
  mx("be", "s034.cyon.net", 10)
  mx("bern.be", "s034.cyon.net", 10)
  mx("bl", "s034.cyon.net", 10)
  mx("bs", "s034.cyon.net", 10)
  mx("fr", "s034.cyon.net", 10)
  mx("ge", "s034.cyon.net", 10)
  mx("gl", "s034.cyon.net", 10)
  mx("gr", "s034.cyon.net", 10)
  mx("ju", "s034.cyon.net", 10)
  mx("lu", "s034.cyon.net", 10)
  mx("ne", "s034.cyon.net", 10)
  mx("nw", "s034.cyon.net", 10)
  mx("ow", "s034.cyon.net", 10)
  mx("sg", "s034.cyon.net", 10)
  mx("sh", "s034.cyon.net", 10)
  mx("so", "s034.cyon.net", 10)
  mx("stadt.zh", "s034.cyon.net", 10)
  mx("steinhausen", "s034.cyon.net", 10)
  mx("sz", "s034.cyon.net", 10)
  mx("tg", "s034.cyon.net", 10)
  mx("ti", "s034.cyon.net", 10)
  mx("ur", "s034.cyon.net", 10)
  mx("vd", "s034.cyon.net", 10)
  mx("vs", "s034.cyon.net", 10)
  mx("winterthur.zh", "s034.cyon.net", 10)
  mx("zg", "s034.cyon.net", 10)
  mx("zh", "s034.cyon.net", 10)
  mx("zs", "s034.cyon.net", 10)
end
