-- Creates dns records for each section
function pps_sections(target)
  -- A records
  alias("ag", target)
  alias("ai", target)
  alias("ar", target)
  alias("bb", target)
  alias("be", target)
  alias("bern.be", target)
  alias("bl", target)
  alias("bs", target)
  alias("fr", target)
  alias("ge", target)
  alias("gl", target)
  alias("gr", target)
  alias("ju", target)
  alias("lu", target)
  alias("ne", target)
  alias("nw", target)
  alias("ow", target)
  alias("sg", target)
  alias("sh", target)
  alias("so", target)
  alias("stadt.zh", target)
  alias("steinhausen", target)
  alias("sz", target)
  alias("tg", target)
  alias("ti", target)
  alias("ur", target)
  alias("vd", target)
  alias("vs", target)
  alias("winterthur.zh", target)
  alias("zg", target)
  alias("zh", target)
  alias("zs", target)

  -- MX records
  mx("ag", target, 10)
  mx("ai", target, 10)
  mx("ar", target, 10)
  mx("bb", target, 10)
  mx("be", target, 10)
  mx("bern.be", target, 10)
  mx("bl", target, 10)
  mx("bs", target, 10)
  mx("fr", target, 10)
  mx("ge", target, 10)
  mx("gl", target, 10)
  mx("gr", target, 10)
  mx("ju", target, 10)
  mx("lu", target, 10)
  mx("ne", target, 10)
  mx("nw", target, 10)
  mx("ow", target, 10)
  mx("sg", target, 10)
  mx("sh", target, 10)
  mx("so", target, 10)
  mx("stadt.zh", target, 10)
  mx("steinhausen", target, 10)
  mx("sz", target, 10)
  mx("tg", target, 10)
  mx("ti", target, 10)
  mx("ur", target, 10)
  mx("vd", target, 10)
  mx("vs", target, 10)
  mx("winterthur.zh", target, 10)
  mx("zg", target, 10)
  mx("zh", target, 10)
  mx("zs", target, 10)
end
